### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_BNO08x#1]
I'm manually running "checklinks" on github readmes.  It turned up some issues.

```
List of broken links and other issues:
https://pypi.org/project/adafruit-circuitpython-bno080/
  Line: 1225
  Code: 404 Not Found
 To do: The link is broken. Double-check that you have not made any typo,
        or mistake in copy-pasting. If the link points to a resource that
        no longer exists, you may want to remove or fix the link.

https://circuitpython.readthedocs.io/projects/bno080/en/latest/
  Line: 1205
  Code: 404 Not Found
 To do: The link is broken. Double-check that you have not made any typo,
        or mistake in copy-pasting. If the link points to a resource that
        no longer exists, you may want to remove or fix the link.
```

**Comment by siddacious** [comment]
This is fixed, however @jepler I have two requests:

Please wait until a library is released to run this check; the first link above will always be broken before the initial release because we only upload to pypi on release. The second can/should be live when the lib is released however it should not be expected to be live until a lib is released

Second request: Please update the script to provide accurate file names and lines. This this and other libraries do not have a  `README.md` but a `README.rst` , and it does not have 1200+ lines. I suspect this is being run against some built version of the file which is fine but it should retain useful information about how to locate the issue
