### ISSUE TITLE
rendering issue with  `activity_classification` docs

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_BNO08x#8]
Note that the list of activities comes before the text that references it:

![image](https://user-images.githubusercontent.com/1183985/98054867-ff72c400-1df0-11eb-8c82-1844f12c9a52.png)

**Comment by dherrada** [comment]
I tried building the docs locally, and it built like it was supposed to. However, it seems it is not building like that here. I tried re-running actions after making a tiny change (it had been too long since the last actions run to just re-run it) but that didn't do anything. 
![Screenshot from 2020-11-25 10-10-02](https://user-images.githubusercontent.com/33632497/100247751-ac2ff500-2f08-11eb-87a2-a398e6ed7eed.png)
The same thing is happening with stability_classification, which would lead me to believe it has something to do with the bullet points for whatever reason.

One other thing I noticed is that locally, the light gray "property" thing appears before the name of the property locally, but is totally absent on the online docs.

**Comment by siddacious** [comment]
@dherrada this seems like a difference in how Sphinx is being run locally and on readthedocs.org; Could be a Sphinx version difference, or a config file difference, however I believe RTD should be using our included config file.

**Comment by jposada202020** [comment]
I build the documents in my readthedocs account and the documents are ok.
https://adafruit-circuitpython-bno08x-jdm.readthedocs.io/en/latest/api.html

We are having a similar issue here
https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/issues/34#issuecomment-825064756

@kmatch98 maybe this is related the way the CI and our local machines are building the documentation

**Comment by dhalbert** [comment]
What versions have you installed? Let's see what `pip3 list |egrep 'sphinx|recommonmark'` says, and compare that to the CI settings.

**Comment by jposada202020** [comment]
So System wise:
```
recommonmark                             0.7.1               
sphinx-autoapi                           1.7.0               
sphinx-rtd-theme                         0.5.1               
sphinxcontrib-applehelp                  1.0.2               
sphinxcontrib-devhelp                    1.0.2               
sphinxcontrib-htmlhelp                   1.0.3               
sphinxcontrib-jsmath                     1.0.1               
sphinxcontrib-qthelp                     1.0.3               
sphinxcontrib-serializinghtml            1.1.4               
sphinxcontrib-svg2pdfconverter           1.1.1   
```
However, the problem is not in my computer, I can build the documents fine.

For the displayIo library is contained in a ven, so doing the same command came empty. Just for information, I coudl build the documentation and create the html using `sphinx-build -E -W -b html . _build/html` without any problem inside.

**Comment by jepler** [comment]
Keep in mind that what the github CI builds is not what RTD builds, that is a separate process.
